### ISSUE TITLE
Contact information when a translation is ready

### ISSUE THREAD

**Issue by willettk** [zooniverse/Docs#1]
The wiki information (https://github.com/zooniverse/Docs/wiki/Translating-Projects) still lists Chris S. and Rob as the contact people for when a translation is ready. Sadly, that needs to be updated. @trouille - who's the point person on this now? @eatyourgreens?

**Comment by marten** [comment]
Just found this repo. Trying to centralise our docs onto developer.zooniverse.org, and need to figure out of this is linked from anywhere (so that we can update the links).

For now though, I've fixed the wiki page.
